name: Build

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        python-version: ["3.14"]

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          token: ${{secrets.RFPROS_TOKEN}}
          submodules: recursive

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build installer
        run: |
          python -m PyInstaller --clean --console --noconfirm --onefile --add-data "files/if820/minidriver-20820A1-uart-patchram.hex;files/if820/" --add-data "files/if91x/minidriver.hex;files/if91x/" --add-data "files/if310/minidriver.hex;files/if310/" --collect-all pyocd --collect-all cmsis_pack_manager -p common_lib/libraries ifx_flasher_cli.py

      - name: Get version
        id: get_version
        run: |
            $version = python -c "import ifx_flasher_cli; print(ifx_flasher_cli.VERSION)"
            echo "VERSION=$version" >> $env:GITHUB_OUTPUT

      - name: Upload artifact
        uses: actions/upload-artifact@v5
        with:
          name: ifx_flasher_cli-${{ runner.os }}-v${{ steps.get_version.outputs.VERSION }}
          path: dist/ifx_flasher_cli*
